services:
  - type: web
    name: book-management
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan key:generate
      php artisan migrate --force
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
    # Apacheが自動的に起動するため、startCommandは不要
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /opt/render/project/src/database/database.sqlite
      - key: APP_URL
        value: https://your-app-name.onrender.com
