services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./book-management:/var/www
    working_dir: /var/www
    depends_on:
      - db
    ports:
      - "9000:9000"

  web:
    image: nginx:alpine
    volumes:
      - ./book-management:/var/www
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - app

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8888:80"
    environment:
      PMA_HOST: db
      PMA_USER: laravel
      PMA_PASSWORD: laravel

volumes:
  db-data: